# Welcome to Jekyll!

title: Jim's Notes
author: Jim Graham
email: jimg@pobox.com
description: >
  Mississippi expat chilling in Texas.

baseurl: ""
domain: jimg72.github.io
url: https://jimg72.github.io

twitter_username: bigjim
instagram_username: bigjim
github_username:  jimg72
linkedin_username: jgraham18
rss: rss

# Build settings
theme: minima
remote_theme: jekyll/minima@v2.5.2
plugins:
  - jekyll-feed
  - jekyll-remote-theme

header_pages:
  - about.md
show_downloads: false

minima:
  date_format: "%Y-%m-%d"
